use_frameworks!

platform :ios, '9.0'

target 'ZSCarouselView-Objc_Example' do
  pod 'ZSCarouselView-Objc', :path => '../'

  target 'ZSCarouselView-Objc_Tests' do
    inherit! :search_paths

    
  end
end
